### ISSUE TITLE
Both ctrl+shift+x and ctrl+shift+e+x are triggering something binded with ctrl+shift+e+x

### ISSUE THREAD

**Issue by ggk-shanmuk** [ccampbell/mousetrap#471] opened 2020-02-03 13:29 UTC
In my observation, the system is not allowing 2 characters combination in a single shortcut but whereas special keys combination is allowed. Hence, we could use either e or x but not both. For example, ctrl+shift+e or ctrl+shift+x.

Currently, both ctrl+shift+x and ctrl+shift+e+x are working because system takes ctrl+shift+x on both cases.

Need some thoughts and insights here.

**Comment by ccampbell** [comment] 2020-02-03 14:11
This is a duplicate of #101. Mousetrap does not support keyboard shortcuts containing two or more regular keys. You can bind a key or a key and modifiers (modifiers being shift, alt, ctrl, and meta).

**Closed as completed by ccampbell** 2020-02-03 14:11 UTC
