### ISSUE TITLE
ctrl++ not working

### ISSUE THREAD

**Issue by marcelboettcher** [ccampbell/mousetrap#266] opened 2015-05-13 14:26 UTC
Hey,

do I need to escape the plus character in any way? ctrl+plus is not working as well.

Thanks a lot!
Marcel

**Comment by ccampbell** [comment] 2015-05-13 14:28
Are you definitely using the latest version? This should have been fixed in 37166a8e7831de6474becb567a7ec1485d3179a1

**Comment by marcelboettcher** [comment] 2015-05-13 14:41
Thanks, I'm using the latest version, but you map the alias 'plus' to '+'. This does not work, because you are doing a string split on the '+' to get the single keys. I guess you need to use '+' as an alias for 'plus'.

**Comment by ccampbell** [comment] 2015-05-13 15:27
The issue does not have to do with the splitting... that would split the string 'ctrl+plus'.  The alias is applied later...  the issue is that I think you actually mean to bind `ctrl+=` or `ctrl+shift+=`.

The best I can do in Mousetrap is automatically map the `plus` key to `shift+=` if you have another modifier added, but that is a little too magical cause I'm not sure the plus key is always `shift+=` on all keyboards.

**Comment by marcelboettcher** [comment] 2015-05-13 15:35
ah ok, thanks! ``ctrl+=`` works as expected on a german keyboard (``strg++``)!

**Closed** 2015-05-13 15:35 UTC
