### ISSUE TITLE
Space + Anything

### ISSUE THREAD

**Issue by eguneys** [ccampbell/mousetrap#323] opened 2016-01-01 09:12 UTC
http://jsfiddle.net/LpLTm/2/

**Comment by tshinnic** [comment] 2016-02-09 21:07
Here's the way I read it (though I'm still learning) so see if this makes sense:

`bind('space+a',...` says "my base character is 'a', with modifiers of 'space'".  But since 'space' is not a valid modifier, it is ignored or thrown away somewhere.  All that remains is the base char 'a', and so when you hit 'a' you get the message "`You pressed: space+a`".

`bind('left+space',...` says "my base character is 'space', with modifiers of 'left'".  Again, 'left' is not a valid modifier, so not usable.  Hitting 'space' will get the message "`You pressed: left+space`"

`bind('space+left',...` : as above, the only useful part is 'left', and so when you hit left arrow you see "`You pressed: space+left`"

The format using '+' is used for things like "`alt+f`" or "`ctrl-a`", which are key _combinations_.

I have to think you meant to use key _sequences_ - detect when one character and then another character is typed.

Using `bind('space a',...`  `bind('left space',...`  `bind('space left',...` all work fine, as checked at your jsfiddle.  Note that instead of '+' the two keys are separated by a space to say these are sequences.  Start out typing the two keys one after another kinda fast.  I don't know what the timeout between keys is, but it is less than one second.

**Comment by ccampbell** [comment] 2016-05-29 14:15
Mousetrap only works with keyboard combinations using modifier keys. This is a duplicate of #101 and unfortunately is not something I plan on supporting.

**Closed by ccampbell** 2016-05-29 14:15 UTC
